name: Rust
on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./hello_thread
      run: cargo build --verbose
    - name: Run
      working-directory: ./hello_thread
      run: cargo run
